#!/bin/bash

# Load $USB_DEVICE_SERIAL_NUMBER
source /etc/lock-unless-smartphone.conf

# Check if USB device with serial number is connected
/usr/bin/lsusb -v 2>/dev/null | grep $USB_DEVICE_SERIAL_NUMBER > /dev/null
exit_status=$?

if [ $exit_status -ne 0 ]; then
    # smartphone not found
    # lock the screen
    sudo --user='#1000' DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /usr/bin/cinnamon-screensaver-command --lock
fi
